"use client";
import React, { useState, useEffect } from "react";
import { Card, CardHeader, CardContent, CardDescription, CardPercentage } from '@/components/ui/card';

// Base interface for stat card data
interface StatCardData {
  title: string;
  value: string;
  percentage: string;
  description: string;
  variant: "dashboard1" | "dashboard2" | "active-bundle" | "revenue" | "slow-moving";
  valueVariant: "bundle-number" | "bundle-amount" | "dashboard1-value" | "dashboard2-value";
  descVariant: "running-campaigns" | "this-month" | "this-week" | "dashboard1-desc" | "dashboard2-desc";
  className: string;
}

// Dashboard 1 specific data
const dashboard1Data: StatCardData[] = [
  {
    title: "AI Profit",
    value: "+38,240 AED",
    percentage: "+12%",
    description: "This Month",
    variant: "dashboard1",
    valueVariant: "dashboard1-value",
    descVariant: "dashboard1-desc",
    className: "w-[61px] self-end font-lato"
  },
  {
    title: "AI Upsell Revenue",
    value: "+38,240 AED",
    percentage: "+12%",
    description: "This Month",
    variant: "dashboard1",
    valueVariant: "dashboard1-value",
    descVariant: "dashboard1-desc",
    className: "w-[61px] self-end font-lato"
  },
  {
    title: "Labor Cost Saved",
    value: "+38,240 AED",
    percentage: "+12%",
    description: "This Month",
    variant: "dashboard1",
    valueVariant: "dashboard1-value",
    descVariant: "dashboard1-desc",
    className: "w-[61px] self-end font-lato"
  },
  {
    title: "Waste Reduced",
    value: "+38,240 AED",
    percentage: "+12%",
    description: "Total value generated by Brewly AI",
    variant: "dashboard1",
    valueVariant: "dashboard1-value",
    descVariant: "dashboard1-desc",
    className: "w-[61px] self-end font-lato"
  }
];

// Dashboard 2 specific data
const dashboard2Data: StatCardData[] = [
  {
    title: "Total Revenue",
    value: "125,400 AED",
    percentage: "+15%",
    description: "Last 30 Days",
    variant: "dashboard2",
    valueVariant: "dashboard2-value",
    descVariant: "dashboard2-desc",
    className: "w-[61px] self-end font-lato"
  },
  {
    title: "Active Users",
    value: "2,845",
    percentage: "+8%",
    description: "Last 30 Days",
    variant: "dashboard2",
    valueVariant: "dashboard2-value",
    descVariant: "dashboard2-desc",
    className: "w-[61px] self-end font-lato"
  },
  {
    title: "Conversion Rate",
    value: "4.8%",
    percentage: "+0.5%",
    description: "Last 30 Days",
    variant: "dashboard2",
    valueVariant: "dashboard2-value",
    descVariant: "dashboard2-desc",
    className: "w-[61px] self-end font-lato"
  },
  {
    title: " Order Value",
    value: "145 AED",
    percentage: "+8%",
    description: "Last 30 Days",
    variant: "dashboard2",
    valueVariant: "dashboard2-value",
    descVariant: "dashboard2-desc",
    className: "w-[61px] self-end font-lato"
  }
];

// Props for renderStatCards component
interface StatCardsProps {
  dashboardType?: 'dashboard1' | 'dashboard2';
  customData?: StatCardData[];
  columns?: 2 | 4;
  animated?: boolean;
  cardClassName?: string;
}

// Main reusable function for stat cards
export const renderStatCards = ({ 
  dashboardType = 'dashboard1', 
  customData, 
  columns = 4,
  animated = true,
  cardClassName
}: StatCardsProps = {}) => {
  // Select data based on dashboard type
  const selectedData = customData || 
    (dashboardType === 'dashboard1' ? dashboard1Data : dashboard2Data);
  
  const [animatedValues, setAnimatedValues] = useState<number[]>(
    selectedData.map(() => animated ? 0 : parseFloat(selectedData[0].value.replace(/[^0-9.]/g, '')))
  );
  const [animatedPercentages, setAnimatedPercentages] = useState<number[]>(
    selectedData.map(() => animated ? 0 : parseFloat(selectedData[0].percentage.replace(/[^0-9.]/g, '')))
  );
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    setIsVisible(true);
    
    if (!animated) {
      const targetValues = selectedData.map(card => 
        parseFloat(card.value.replace(/[^0-9.]/g, ''))
      );
      const targetPercentages = selectedData.map(card => 
        parseFloat(card.percentage.replace(/[^0-9.]/g, ''))
      );
      setAnimatedValues(targetValues);
      setAnimatedPercentages(targetPercentages);
      return;
    }

    const targetValues = selectedData.map(card => 
      parseFloat(card.value.replace(/[^0-9.]/g, ''))
    );

    const targetPercentages = selectedData.map(card => 
      parseFloat(card.percentage.replace(/[^0-9.]/g, ''))
    );

    const duration = 2000;
    const steps = 60;
    const stepDuration = duration / steps;

    let currentStep = 0;
    const interval = setInterval(() => {
      currentStep++;
      const progress = currentStep / steps;
      const easeOutQuad = 1 - (1 - progress) * (1 - progress);

      setAnimatedValues(targetValues.map(target => 
        Math.floor(target * easeOutQuad)
      ));

      setAnimatedPercentages(targetPercentages.map(target => 
        Math.floor(target * easeOutQuad)
      ));

      if (currentStep >= steps) {
        setAnimatedValues(targetValues);
        setAnimatedPercentages(targetPercentages);
        clearInterval(interval);
      }
    }, stepDuration);

    return () => clearInterval(interval);
  }, [selectedData, animated]);

  const gridClasses = columns === 2 
    ? "grid grid-cols-1 md:grid-cols-2 gap-4" 
    : "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4";

  return (
    <div className={gridClasses}>
      {selectedData.map((card, index) => (
        <Card 
          key={index} 
          variant={card.variant}
          className={`transform transition-all duration-700 hover:scale-100 hover:shadow-xl cursor-pointer ${cardClassName ?? ''} ${
            isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4' 
          }`}
        >
          <div className="flex justify-between items-center px-3 py-4">
            <CardHeader 
              variant={card.variant}
              className="transition-colors duration-300 text-sm font-medium text-gray-700"
            >
              <div>{card.title}</div>
            </CardHeader>
            <CardPercentage 
              variant={card.variant as 'dashboard1' | 'dashboard2'}
              className="font-lato px-3 py-1 rounded text-[14px] font-semibold" 
              value={`${animatedPercentages[index] > 0 ? '+' : ''}${animatedPercentages[index]}%`}
            />
          </div>
          
          <div className="px-3 py-4">
            <CardContent 
              variant={card.valueVariant}
              className={`transition-all duration-300 hover:scale-100 text-[24px] font-semibold whitespace-nowrap`}
            >
              {card.value.includes('AED') 
                ? `${animatedValues[index] > 0 ? '+' : ''}${animatedValues[index].toLocaleString()} AED`
                : card.value.includes('%')
                  ? `${animatedValues[index]}%`
                  : animatedValues[index].toLocaleString()
              }
            </CardContent>
            <CardDescription 
              variant={card.descVariant}
              className="transition-opacity duration-300 text-xs mt-2"
            >
              {card.description}
            </CardDescription>
          </div>
        </Card>
      ))}
    </div>
  );
};

// For backward compatibility
export const DashboardStats = renderStatCards;
export default renderStatCards;