"use client";

import React from "react";

export function TotalProfitChart() {
  return (
    <div
      className="w-full bg-white rounded-[16px] border border-[#E4E4E7] p-[20px] px-[24px]"
    >
      {/* Header */}
      <div className="mb-4">
        <div className="font-lato font-semibold text-[16px] leading-6 text-[#1E1E1E] mb-2">Total Profit Made By Promoting Slow Moving Items</div>
        <div className="flex items-baseline gap-2">
          <span className="font-lato font-bold text-[24px] leading-[32px] text-[#1E1E1E]">400 AED</span>
          <span className="font-normal text-[14px] text-[#10B981]">+8%</span>
        </div>
        <div className="font-lato font-normal text-[12px] text-[#787777] mt-1">Total profit generated by AI bundles</div>
      </div>

      {/* Chart Area */}
      <div
        className="w-full h-[180px] relative"
      >
        <svg width="100%" height="180" viewBox="0 0 500 180" preserveAspectRatio="none">
          {/* Grid lines */}
          <line x1="0" y1="36" x2="500" y2="36" stroke="#F5F5F5" strokeWidth="1" />
          <line x1="0" y1="72" x2="500" y2="72" stroke="#F5F5F5" strokeWidth="1" />
          <line x1="0" y1="108" x2="500" y2="108" stroke="#F5F5F5" strokeWidth="1" />
          <line x1="0" y1="144" x2="500" y2="144" stroke="#F5F5F5" strokeWidth="1" />
          
          {/* Red line (upper) */}
          <path
            d="M 0 80 L 50 70 L 100 90 L 150 60 L 200 75 L 250 50 L 300 65 L 350 45 L 400 55 L 450 40 L 500 30"
            fill="none"
            stroke="#EF4444"
            strokeWidth="2.5"
          />
          
          {/* Green line (lower) */}
          <path
            d="M 0 140 L 50 130 L 100 145 L 150 120 L 200 125 L 250 110 L 300 105 L 350 95 L 400 100 L 450 85 L 500 80"
            fill="none"
            stroke="#10B981"
            strokeWidth="2.5"
          />
        </svg>
      </div>

      {/* Legend */}
      <div className="flex gap-4 mt-3 text-[12px] text-[#787777]">
        <div className="flex items-center gap-[6px]">
          <div className="w-[12px] h-[12px] bg-[#EF4444] rounded-[2px]"></div>
          <span>Manual Bundle</span>
        </div>
        <div className="flex items-center gap-[6px]">
          <div className="w-[12px] h-[12px] bg-[#10B981] rounded-[2px]"></div>
          <span>AI Generated</span>
        </div>
      </div>

      {/* Date Range */}
      <div className="mt-3 font-lato text-[12px] text-[#787777]">Jan 2024 - Dec 2024</div>
    </div>
  );
}
