"use client";

import React from "react";

export function TotalProfitChart() {
  return (
    <div
      style={{
        width: "100%",
        background: "#FFFFFF",
        borderRadius: 16,
        border: "1px solid #E4E4E7",
        padding: "20px 24px",
      }}
    >
      {/* Header */}
      <div style={{ marginBottom: 16 }}>
        <div
          style={{
            fontFamily: "Lato, sans-serif",
            fontWeight: 600,
            fontSize: 16,
            lineHeight: "24px",
            color: "#1E1E1E",
            marginBottom: 8,
          }}
        >
          Total Profit Made By Promoting Slow Moving Items
        </div>
        <div style={{ display: "flex", alignItems: "baseline", gap: 8 }}>
          <span
            style={{
              fontFamily: "Lato, sans-serif",
              fontWeight: 700,
              fontSize: 24,
              lineHeight: "32px",
              color: "#1E1E1E",
            }}
          >
            400 AED
          </span>
          <span
            style={{
              fontWeight: 400,
              fontSize: 14,
              color: "#10B981",
            }}
          >
            +8%
          </span>
        </div>
        <div
          style={{
            fontFamily: "Lato, sans-serif",
            fontWeight: 400,
            fontSize: 12,
            color: "#787777",
            marginTop: 4,
          }}
        >
          Total profit generated by AI bundles
        </div>
      </div>

      {/* Chart Area */}
      <div
        style={{
          width: "100%",
          height: 180,
          position: "relative",
        }}
      >
        <svg width="100%" height="180" viewBox="0 0 500 180" preserveAspectRatio="none">
          {/* Grid lines */}
          <line x1="0" y1="36" x2="500" y2="36" stroke="#F5F5F5" strokeWidth="1" />
          <line x1="0" y1="72" x2="500" y2="72" stroke="#F5F5F5" strokeWidth="1" />
          <line x1="0" y1="108" x2="500" y2="108" stroke="#F5F5F5" strokeWidth="1" />
          <line x1="0" y1="144" x2="500" y2="144" stroke="#F5F5F5" strokeWidth="1" />
          
          {/* Red line (upper) */}
          <path
            d="M 0 80 L 50 70 L 100 90 L 150 60 L 200 75 L 250 50 L 300 65 L 350 45 L 400 55 L 450 40 L 500 30"
            fill="none"
            stroke="#EF4444"
            strokeWidth="2.5"
          />
          
          {/* Green line (lower) */}
          <path
            d="M 0 140 L 50 130 L 100 145 L 150 120 L 200 125 L 250 110 L 300 105 L 350 95 L 400 100 L 450 85 L 500 80"
            fill="none"
            stroke="#10B981"
            strokeWidth="2.5"
          />
        </svg>
      </div>

      {/* Legend */}
      <div style={{ display: "flex", gap: 16, marginTop: 12, fontSize: 12, color: "#787777" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
          <div style={{ width: 12, height: 12, background: "#EF4444", borderRadius: 2 }}></div>
          <span>Manual Bundle</span>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
          <div style={{ width: 12, height: 12, background: "#10B981", borderRadius: 2 }}></div>
          <span>AI Generated</span>
        </div>
      </div>

      {/* Date Range */}
      <div
        style={{
          marginTop: 12,
          fontFamily: "Lato, sans-serif",
          fontSize: 12,
          color: "#787777",
        }}
      >
        Jan 2024 - Dec 2024
      </div>
    </div>
  );
}
